### ISSUE TITLE
[Bug]: When viewing remote results, the workflow containing Chinese characters appears garbled

### ISSUE THREAD

**Issue by ahai-code** [apache/hop#3590]
### Apache Hop version?

2.6.0

### Java version?

11.0.2

### Operating system

Windows

### What happened?

I created a workflow (this workflow contains Chinese characters), see Figure 1, using the remote (Hop remote workflow engine) way to run, the output of the log is normal, but when I view the results (Location type is Remote location, see Figure 2) appeared garbled, see Figure 3.
![image](https://github.com/apache/hop/assets/61728435/b100250b-ca9d-4b48-beec-33865cec9c0f)
![image (1)](https://github.com/apache/hop/assets/61728435/2011a875-fb09-423c-b07b-2cdc9472d4d2)
![image (2)](https://github.com/apache/hop/assets/61728435/e4a188a5-2014-436f-9a34-a6042ec099d8)

### Issue Priority

Priority: 2

### Issue Component

Component: Actions, Component: API, Component: Hop Gui, Component: Hop Server

**Comment by hansva** [comment]
Could you test with Hop 2.7, this issue should be resolved #3356

**Comment by ahai-code** [comment]
Thanks a lot for the answer, I tested again with the latest version 2.7.0 (client and docker image) but the issue persists, maybe it is different from [#3356.](https://github.com/apache/hop/issues/3356)

**Comment by nadment** [comment]
The same problem is also visible in the metrics tab.

Local execution
![image](https://github.com/apache/hop/assets/39568358/048b9551-1f9d-413a-a99c-d0cad48426d1)

Remote server execution
![image](https://github.com/apache/hop/assets/39568358/9e5de4e9-ff0a-43be-aba1-01e6573ad64c)

**Comment by nadment** [comment]
Charset problems seem to have been corrected with https://github.com/apache/hop/pull/3599

![image](https://github.com/apache/hop/assets/39568358/77f11464-d7b5-402a-9517-6717ea2fbf7d)

**Comment by ahai-code** [comment]
The problem doesn't seem to be completely solved, I downloaded the latest version 2.8.0, created a workflow to test it, and there is still Chinese gibberish when getting the workflow remote results.

Figure 1. Workflow remote logs print properly.
<img width="842" alt="1710688660078" src="https://github.com/apache/hop/assets/61728435/b1dda3b9-4b00-4886-9177-af649829c436">

Figure 2. Workflow remote results appear garbled, including the workflow name, log, and the name of the action in the workflow.
<img width="913" alt="1710688700505" src="https://github.com/apache/hop/assets/61728435/90d36693-2c28-44a9-9f43-042822feead9">

Figure 3. Double-click to enter the operation of the pipeline type, which also has a lot of garbled code, including pipeline names, conversion names and logs, etc.
<img width="895" alt="1710688752358" src="https://github.com/apache/hop/assets/61728435/d3eb04cc-488c-4543-a9a7-bcf4f94d8282">

**Comment by nadment** [comment]
I'm reopening the issue. I reproduce the bug with the following "Execution Information Location":

![image](https://github.com/apache/hop/assets/39568358/227dab2f-6bb5-44d0-b279-0258fcf0f72a)

**Comment by hansva** [comment]
@ahai-code, could you test with a latest build from [here](https://repository.apache.org/content/repositories/snapshots/org/apache/hop/hop-client/2.9.0-SNAPSHOT/) then we know the issues are resolved in the next version

**Comment by ahai-code** [comment]
Well, I downloaded "hop-client-2.9.0-20240318.234909-1.zip" from the link, and hop-server (Docker image) is still using 2.8.0, and testing revealed that when using the remote method to run the workflow and pipeline, this error message appears, as shown in Figure 1. Is it because I am not using the same version (2.9.0-20240318.234909-1) of the Docker image as the client?
<img width="1250" alt="1710840398612" src="https://github.com/apache/hop/assets/61728435/f809e30f-a09b-4453-b7c5-ba69a254132a">
<img width="1243" alt="1710840503391" src="https://github.com/apache/hop/assets/61728435/0e20d5e3-abf2-4e90-b008-ba9d1b1011c3">

**Comment by hansva** [comment]
Hi @ahai-code for docker images you can use the 2.9.0-SNAPSHOT or Development tags:
https://hub.docker.com/r/apache/hop/tags

**Comment by ahai-code** [comment]
@hansva Thank you, it's because the client and hop server versions are not the same. And I just created a remote workflow to test it, and the garbled Chinese issue is resolved. @nadment Thank you again for your patience in solving this problem, which has helped me a lot in using the software.
<img width="990" alt="1710852237629" src="https://github.com/apache/hop/assets/61728435/0bb946f0-e00d-4f7d-bd47-ad34fb250324">
